# Credits for the base: https://github.com/cammellos/typst-blue-header-cv/blob/main/.github/workflows/main.yml

permissions:
  contents: write
  
name: Building the CV

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@main

    - name: use typst
      run: typst --version
      shell: bash

    - name: Building the CV
      run: make
      shell: bash

    # - name: Commit updated resume.pdf
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     author_name: "github-actions"
    #     author_email: "github-actions@github.com"
    #     message: "Update resume.pdf after regeneration [skip ci]"
    #     add: "output/resume.pdf"
    #     push: true
    #     push-token: ${{ secrets.GITHUB_TOKEN }}

    # Commit and push all changed files.
    - name: Committing updated resume
      if: github.event_name == 'push'
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git commit -a -m "Updating resume.pdf after regeneration [skip ci]" || echo "No changes to commit"
        git push