# Credits for the base: https://github.com/cammellos/typst-blue-header-cv/blob/main/.github/workflows/main.yml

permissions:
  contents: write
  
name: Building the CV

on: push
jobs:
  build-cv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Typst
      uses: typst-community/setup-typst@v4

    - name: Use typst
      run: typst --version
      shell: bash

    - name: Building the CV
      run: make
      shell: bash
    
    - name: Committing updated resume
      if: github.event_name == 'push'
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git commit -a -m "Updating resume.pdf after regeneration [skip ci]" || echo "No changes to commit"
        git push