# Credits for the base: https://github.com/cammellos/typst-blue-header-cv/blob/main/.github/workflows/main.yml

name: Building the CV

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Setup env"
      uses: JRMurr/direnv-nix-action@main

    - name: use typst
      run: typst --version
      shell: bash

    - name: Building the CV
      run: make
      shell: bash

    - name: Commit updated resume.pdf
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "github-actions"
        author_email: "github-actions@github.com"
        message: "Update resume.pdf after regeneration [skip ci]"
        add: "output/resume.pdf"
        push: true
        push-token: ${{ secrets.GITHUB_TOKEN }}